# Generated by Django 5.0.4 on 2024-05-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categroy',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
