# Generated by Django 5.0.4 on 2024-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0005_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_link',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
